/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ActorId = string;
export type DisplayName = string | null;
export type Bio = string | null;
export type Email = string | null;
export type HasPhoto = boolean;
export type CreatedAt = string | null;
export type UpdatedAt = string | null;

export interface EditProfilePageData {
  profile: UserProfile;
  [k: string]: unknown;
}
export interface UserProfile {
  actor_id: ActorId;
  display_name?: DisplayName;
  bio?: Bio;
  email?: Email;
  has_photo?: HasPhoto;
  created_at?: CreatedAt;
  updated_at?: UpdatedAt;
  [k: string]: unknown;
}
