/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Label = string;
export type TagName = string;
export type JsUrls = string[];
export type CssUrls = string[];
export type SortOrder = number;
export type Icon = string;

export interface ProfileSectionData {
  id: Id;
  label: Label;
  tag_name: TagName;
  js_urls?: JsUrls;
  css_urls?: CssUrls;
  sort_order?: SortOrder;
  icon?: Icon;
  [k: string]: unknown;
}
